version: '3'
services:
  mongodb:
    image: mongo:6.0-focal
    restart: always
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: "123456789"
    volumes:
      - data:/data/db
    ports:
      - 127.0.0.1:27017:27017
      - 127.0.0.1:31236:27017

volumes:
  data:
